include $(TOPDIR)/config.mk

src-y += AdPlanningData.cpp
src-y += AdRtbEngine.cpp
src-y += AdRtbCtr.cpp
src-y += AdRtbProtect.cpp
src-y += AdRtbDealRank.cpp
src-y += AdClassifier.cpp
src-y += AdFeature_extractor.cpp
src-y += AdRtbEngCtr.cpp

lib-y = engine.a
include $(TOPDIR)/build.mk
