include $(TOPDIR)/config.mk
src-y += MiaoZhen/
src-y += Google/
src-y += JuXiao/
src-y += TanX/
src-y += YouKu/
src-y += WeiBo/
src-y += InMoBi/
src-y += Baidu/
src-y += Gdt/
src-y += Sohu/
src-y += Tencent/
src-y += AiQiYi/
src-y += Mango/
src-y += AiTou/

include $(TOPDIR)/build.mk
