include $(TOPDIR)/config.mk

src-y += AdMd5.cpp
src-y += AdRedisCli.cpp
src-y += AdRtbConfig.cpp
src-y += AdAcbm.cpp
src-y += AdThread.cpp
src-y += AdIpc.cpp
src-y += AdAes.cpp

lib-m = util.so
include $(TOPDIR)/build.mk
