include $(TOPDIR)/config.mk

src-y += AdFilterTime.cpp
src-y += AdFilterAdExchange.cpp
src-y += AdFilterPid.cpp
src-y += AdFilterArea.cpp
src-y += AdFilterMobileOperator.cpp
src-y += AdFilterMobileDevice.cpp
src-y += AdFilterMobileConnect.cpp
src-y += AdFilterParameter.cpp
src-y += AdFilterBan.cpp
src-y += AdFilterLandingPage.cpp
src-y += AdFilterSize.cpp
src-y += AdFilterRealTime.cpp
src-y += AdFilterFrequence.cpp
src-y += AdFilterMark.cpp
src-y += AdFilterTanx.cpp
src-y += AdFilterUserAgent.cpp
src-y += AdMap.cpp
src-y += AdUserInfo.cpp
src-y += AdRtbFilters.cpp

lib-y = filters.a
include $(TOPDIR)/build.mk
